### ISSUE TITLE
关于nstimer 释放

### ISSUE THREAD

**Issue by mxpasser** [fishmwei/MWMarqueeView#1]
@fishmwei 你好，很感谢你的跑马灯效果。参看了源码后，有个问题请教，里面scheduledtimerwithtimeinterval这么创建了nstimer，不过没有找到释放timer的地方。

**Comment by fishmwei** [comment]
谢谢反馈， scheduledtimerwithtimeinterval 创建的一次性timer会自动释放。 

不过原先代码中， 有一些问题， block里没有使用弱引用 存在资源未释放的问题。 新版本(1.0.1)中更新
